"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccessorType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
/**
 * "description": "Specifies if the attribute is a scalar, vector, or matrix."
 */
var AccessorType;
(function (AccessorType) {
    AccessorType[AccessorType["SCALAR"] = 0] = "SCALAR";
    AccessorType[AccessorType["VEC2"] = 1] = "VEC2";
    AccessorType[AccessorType["VEC3"] = 2] = "VEC3";
    AccessorType[AccessorType["VEC4"] = 3] = "VEC4";
    AccessorType[AccessorType["MAT2"] = 4] = "MAT2";
    AccessorType[AccessorType["MAT3"] = 5] = "MAT3";
    AccessorType[AccessorType["MAT4"] = 6] = "MAT4";
})(AccessorType || (exports.AccessorType = AccessorType = {}));
