"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.CameraType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
/**
 * "description": "Specifies if the camera uses a perspective or orthographic projection."
 * "gltf_detailedDescription": "Specifies if the camera uses a perspective or orthographic projection.  Based on this, either the camera's `perspective` or `orthographic` property will be defined."
 */
var CameraType;
(function (CameraType) {
    CameraType[CameraType["perspective"] = 0] = "perspective";
    CameraType[CameraType["orthographic"] = 1] = "orthographic";
})(CameraType || (exports.CameraType = CameraType = {}));
