"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Image = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var flatbuffers = require("flatbuffers");
/**
 *----------------------------------------------------------------------------
 * Image
 * "description": "Image data used to create a texture. Image can be referenced by URI or `bufferView` index. `mimeType` is required in the latter case."
 */
var Image = /** @class */ (function () {
    function Image() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Image.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Image.getRootAsImage = function (bb, obj) {
        return (obj || new Image()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    Image.getSizePrefixedRootAsImage = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Image()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    /**
     * Dictionary object with extension-specific objects.
     */
    Image.prototype.extensions = function (index) {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
    };
    Image.prototype.extensionsLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    Image.prototype.extensionsArray = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    };
    /**
     * Application-specific data.
     */
    Image.prototype.extras = function (index) {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
    };
    Image.prototype.extrasLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    Image.prototype.extrasArray = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    };
    /**
     * "description": "The index of the bufferView that contains the image. Use this instead of the image's uri property."
     */
    Image.prototype.bufferView = function () {
        var offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : -1;
    };
    Image.prototype.mimeType = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    Image.prototype.name = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    Image.prototype.uri = function (optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    };
    Image.startImage = function (builder) {
        builder.startObject(6);
    };
    Image.addExtensions = function (builder, extensionsOffset) {
        builder.addFieldOffset(0, extensionsOffset, 0);
    };
    Image.createExtensionsVector = function (builder, data) {
        builder.startVector(1, data.length, 1);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    };
    Image.startExtensionsVector = function (builder, numElems) {
        builder.startVector(1, numElems, 1);
    };
    Image.addExtras = function (builder, extrasOffset) {
        builder.addFieldOffset(1, extrasOffset, 0);
    };
    Image.createExtrasVector = function (builder, data) {
        builder.startVector(1, data.length, 1);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    };
    Image.startExtrasVector = function (builder, numElems) {
        builder.startVector(1, numElems, 1);
    };
    Image.addBufferView = function (builder, bufferView) {
        builder.addFieldInt32(2, bufferView, -1);
    };
    Image.addMimeType = function (builder, mimeTypeOffset) {
        builder.addFieldOffset(3, mimeTypeOffset, 0);
    };
    Image.addName = function (builder, nameOffset) {
        builder.addFieldOffset(4, nameOffset, 0);
    };
    Image.addUri = function (builder, uriOffset) {
        builder.addFieldOffset(5, uriOffset, 0);
    };
    Image.endImage = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    Image.createImage = function (builder, extensionsOffset, extrasOffset, bufferView, mimeTypeOffset, nameOffset, uriOffset) {
        Image.startImage(builder);
        Image.addExtensions(builder, extensionsOffset);
        Image.addExtras(builder, extrasOffset);
        Image.addBufferView(builder, bufferView);
        Image.addMimeType(builder, mimeTypeOffset);
        Image.addName(builder, nameOffset);
        Image.addUri(builder, uriOffset);
        return Image.endImage(builder);
    };
    return Image;
}());
exports.Image = Image;
