"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.SamplerFilter = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
/**
 *----------------------------------------------------------------------------
 * "gltf_detailedDescription": "All valid values correspond to WebGL enums."
 */
var SamplerFilter;
(function (SamplerFilter) {
    SamplerFilter[SamplerFilter["NEAREST"] = 9728] = "NEAREST";
    SamplerFilter[SamplerFilter["LINEAR"] = 9729] = "LINEAR";
    SamplerFilter[SamplerFilter["NEAREST_MIPMAP_NEAREST"] = 9984] = "NEAREST_MIPMAP_NEAREST";
    SamplerFilter[SamplerFilter["LINEAR_MIPMAP_NEAREST"] = 9985] = "LINEAR_MIPMAP_NEAREST";
    SamplerFilter[SamplerFilter["NEAREST_MIPMAP_LINEAR"] = 9986] = "NEAREST_MIPMAP_LINEAR";
    SamplerFilter[SamplerFilter["LINEAR_MIPMAP_LINEAR"] = 9987] = "LINEAR_MIPMAP_LINEAR";
})(SamplerFilter || (exports.SamplerFilter = SamplerFilter = {}));
