"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.WrapMode = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
/**
 * "gltf_detailedDescription": "All valid values correspond to WebGL enums."
 */
var WrapMode;
(function (WrapMode) {
    WrapMode[WrapMode["REPEAT"] = 10497] = "REPEAT";
    WrapMode[WrapMode["CLAMP_TO_EDGE"] = 33071] = "CLAMP_TO_EDGE";
    WrapMode[WrapMode["MIRRORED_REPEAT"] = 33648] = "MIRRORED_REPEAT";
})(WrapMode || (exports.WrapMode = WrapMode = {}));
